version: '3.9'
    
services:
  bot:
    container_name: bot_playground
    build: 
      context: ./
    restart: always
    ports:
      - 3000:3000
    environment:
      - DB_URI=mongodb://mongo/bot_playground
    depends_on:
      - mongo
    links:
      - mongo
  mongo:
    image: mongo
    container_name: bot_mongo
    restart: always
    ports:
      - "27019:27017"
    environment:
      MONGO_INITDB_DATABASE: bot_playground
    expose:
      - 27019