FROM node:18-bullseye as bot
WORKDIR /app
COPY package.json pnpm-lock.yaml ./
RUN npm install --global pnpm && \
    pnpm install --frozen-lockfile
COPY . .
ARG VITE_URL
ARG VITE_PUSHER_ID
ARG VITE_PUSHER_PK
ARG VITE_PUSHER_SK
ARG VITE_PUSHER_CLUSTER

ENV VITE_URL=$VITE_URL
ENV VITE_PUSHER_ID=$VITE_PUSHER_ID
ENV VITE_PUSHER_PK=$VITE_PUSHER_PK
ENV VITE_PUSHER_SK=$VITE_PUSHER_SK
ENV VITE_PUSHER_CLUSTER=$VITE_PUSHER_CLUSTER

RUN pnpm run build
EXPOSE 8080
CMD ["pnpm", "run", "deploy"]